import { Subject, Note, Assignment, Teacher, RoutineSlot } from './types';

export const fallbackSubjects: Subject[] = [
  {
    id: 'CSE 3201',
    code: 'CSE 3201',
    name: 'Mathematical Analysis for Computer Science',
    short_name: 'CSE',
    color: 'indigo',
    credit_hours: 3,
  },
  {
    id: 'CSE 3202',
    code: 'CSE 3202',
    name: 'Theory of Computation',
    short_name: 'CSE',
    color: 'emerald',
    credit_hours: 3,
  },
  {
    id: 'CSE 3203',
    code: 'CSE 3203',
    name: 'Computer Networks',
    short_name: 'CSE',
    color: 'amber',
    credit_hours: 3,
  },
  {
    id: 'CSE 3204',
    code: 'CSE 3204',
    name: 'Computer Networks Lab',
    short_name: 'CSE',
    color: 'violet',
    credit_hours: 1.5,
  },
];

export const fallbackNotes: Note[] = [
  {
    id: 19,
    title: 'Math Lecture 01 - Propositional Logic',
    description: 'Foundations of mathematical logic, propositions, and truth tables.',
    subject_id: 'CSE 3201',
    type: 'pdf',
    url: 'https://urzdhkkpfaibpddnaygl.supabase.co/storage/v1/object/public/class-materials/l3jwhlzy4m_1782820857462.pdf',
    created_at: '2026-06-30T12:00:58.34294+00:00',
    attachments: [
      {
        name: 'Math Lecture 01.pdf',
        url: 'https://urzdhkkpfaibpddnaygl.supabase.co/storage/v1/object/public/class-materials/l3jwhlzy4m_1782820857462.pdf',
        type: 'pdf',
      },
    ],
  },
  {
    id: 20,
    title: 'Math Lecture 02 - Predicate Calculus & Quantifiers',
    description: 'First order predicate logic, universal and existential quantifiers.',
    subject_id: 'CSE 3201',
    type: 'pdf',
    url: 'https://urzdhkkpfaibpddnaygl.supabase.co/storage/v1/object/public/class-materials/l3jwhlzy4m_1782820857462.pdf',
    created_at: '2026-06-30T12:05:00.000Z',
    attachments: [
      {
        name: 'Math Lecture 02.pdf',
        url: 'https://urzdhkkpfaibpddnaygl.supabase.co/storage/v1/object/public/class-materials/l3jwhlzy4m_1782820857462.pdf',
        type: 'pdf',
      },
    ],
  },
  {
    id: 21,
    title: 'TOC Lecture 01 - Finite Automata & Regular Languages',
    description: 'Deterministic and Non-deterministic Finite Automata (DFA/NFA).',
    subject_id: 'CSE 3202',
    type: 'pdf',
    url: 'https://urzdhkkpfaibpddnaygl.supabase.co/storage/v1/object/public/class-materials/l3jwhlzy4m_1782820857462.pdf',
    created_at: '2026-07-02T10:15:00.000Z',
    attachments: [
      {
        name: 'TOC Lecture 01.pdf',
        url: 'https://urzdhkkpfaibpddnaygl.supabase.co/storage/v1/object/public/class-materials/l3jwhlzy4m_1782820857462.pdf',
        type: 'pdf',
      },
    ],
  },
  {
    id: 22,
    title: 'Networks Lecture 01 - OSI Model & TCP/IP Protocol Stack',
    description: 'Layered network architectures, packet switching vs circuit switching.',
    subject_id: 'CSE 3203',
    type: 'pdf',
    url: 'https://urzdhkkpfaibpddnaygl.supabase.co/storage/v1/object/public/class-materials/l3jwhlzy4m_1782820857462.pdf',
    created_at: '2026-07-05T09:00:00.000Z',
    attachments: [
      {
        name: 'Networks Lecture 01.pdf',
        url: 'https://urzdhkkpfaibpddnaygl.supabase.co/storage/v1/object/public/class-materials/l3jwhlzy4m_1782820857462.pdf',
        type: 'pdf',
      },
    ],
  },
];

export const fallbackAssignments: Assignment[] = [
  {
    id: 1,
    title: 'Networks Assignment 1: Subnetting & CIDR Calculation',
    description: 'Solve problem sets 1 to 5 from chapter 4. Submit PDF document.',
    subject_id: 'CSE 3203',
    due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
    created_at: '2026-07-01T12:00:00.000Z',
  },
  {
    id: 2,
    title: 'TOC Problem Set 2: NFA to DFA Conversion',
    description: 'Subset construction algorithm implementation and diagram submission.',
    subject_id: 'CSE 3202',
    due_date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'pending',
    created_at: '2026-07-03T14:30:00.000Z',
  },
  {
    id: 3,
    title: 'Math Proofs: Mathematical Induction & Recurrence Relations',
    description: 'Complete questions 10-18 from Section 5.2.',
    subject_id: 'CSE 3201',
    due_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: 'submitted',
    created_at: '2026-06-25T08:00:00.000Z',
  },
];

export const fallbackTeachers: Teacher[] = [
  {
    id: 1,
    name: 'Dr. Abdur Rahman',
    role: 'Associate Professor',
    email: 'arahman@university.edu',
    phone: '+880 1712-345678',
    room: 'Room 402, Dept Building',
    office_hours: 'Sun & Tue: 2:00 PM - 4:00 PM',
    initials: 'AR',
  },
  {
    id: 2,
    name: 'Prof. Kamal Ahmed',
    role: 'Professor & Head',
    email: 'kahmed@university.edu',
    phone: '+880 1819-876543',
    room: 'Room 501, Dept Building',
    office_hours: 'Mon & Wed: 11:00 AM - 1:00 PM',
    initials: 'KA',
  },
  {
    id: 3,
    name: 'Ms. Fatima Akter',
    role: 'Assistant Professor',
    email: 'fakter@university.edu',
    phone: '+880 1911-234567',
    room: 'Room 310, Dept Building',
    office_hours: 'Saturday: 10:00 AM - 12:00 PM',
    initials: 'FA',
  },
  {
    id: 4,
    name: 'Dr. Imran Khan',
    role: 'Assistant Professor',
    email: 'ikhan@university.edu',
    phone: '+880 1612-987654',
    room: 'Room 205, Dept Building',
    office_hours: 'Thu: 3:00 PM - 5:00 PM',
    initials: 'IK',
  },
];

export const fallbackRoutineSlots: RoutineSlot[] = [
  {
    day_name: 'Saturday',
    time_slot_index: 0,
    time_label: '09:00 - 10:00',
    subject_id: 'CSE 3201',
    teacher_name: 'Dr. Abdur Rahman',
    room: 'Room 301',
    type: 'lecture',
  },
  {
    day_name: 'Saturday',
    time_slot_index: 1,
    time_label: '10:00 - 11:00',
    subject_id: 'CSE 3202',
    teacher_name: 'Prof. Kamal Ahmed',
    room: 'Room 301',
    type: 'lecture',
  },
  {
    day_name: 'Saturday',
    time_slot_index: 2,
    time_label: '11:30 - 01:00',
    subject_id: 'CSE 3204',
    teacher_name: 'Ms. Fatima Akter',
    room: 'Network Lab 2',
    type: 'lab',
  },
  {
    day_name: 'Sunday',
    time_slot_index: 0,
    time_label: '09:00 - 10:30',
    subject_id: 'CSE 3203',
    teacher_name: 'Dr. Imran Khan',
    room: 'Room 205',
    type: 'lecture',
  },
  {
    day_name: 'Sunday',
    time_slot_index: 1,
    time_label: '11:00 - 12:30',
    subject_id: 'CSE 3201',
    teacher_name: 'Dr. Abdur Rahman',
    room: 'Room 205',
    type: 'lecture',
  },
  {
    day_name: 'Monday',
    time_slot_index: 0,
    time_label: '10:00 - 11:30',
    subject_id: 'CSE 3202',
    teacher_name: 'Prof. Kamal Ahmed',
    room: 'Room 402',
    type: 'lecture',
  },
  {
    day_name: 'Monday',
    time_slot_index: 1,
    time_label: '12:00 - 01:30',
    subject_id: 'CSE 3203',
    teacher_name: 'Dr. Imran Khan',
    room: 'Room 402',
    type: 'lecture',
  },
];
